
server:
  port: 8084
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: content-conveyor
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: conveyor
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  liquibase:
    enabled: true
    change-log: ./db/changelog/changelog-master.yml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.0
          max-tokens: 8000 # Токенов специально немного меньше максимума
  cloud:
    openfeign:
      client:
        config:
          tg-chats-collector:
            connectTimeout: 600000
            readTimeout: 600000

retelling:
  executors:
    tg-listener:
      threads: 10
      queue-capacity: 1000
  scheduled-jobs:
    source-parsing:
      article-cron: 0 0 8 * * *
      tg-cron: 0 * * * * *
    event-processing:
      cron: "*/10 * * * * *"
  rate:
    threshold: 60 # Оценка материала должна быть выше данного значения, для его публикации
  data-finder:
    article:
      period-of-days-to-look-for: 2

  hardcoded-publishing-channels:
    chat-id: ${PUBLISHING_CHAT_ID}
    rate-tg-topic-id: ${RATE_TG_TOPIC_ID}
    debug-chat-id: ${DEBUG_CHAT_ID}
    debug-topic-id: ${DEBUG_TG_TOPIC_ID}
    java-medium-topic-id: ${JAVA_RETELLING_TG_TOPIC_ID}
    java-dzone-topic-id: ${JAVA_RETELLING_TG_TOPIC_ID}
    tg-message-batch-topic-id: ${TG_MESSAGE_BATCH_RETELLING_TG_TOPIC_ID}

  hardcoded-prompts:
    youtube-retelling: ${YOUTUBE_RETELLING_PROMPT}
    java-article-rate-material: ${JAVA_ARTICLE_RATE_MATERIAL_PROMPT}
    java-article-retelling: ${JAVA_ARTICLE_RETELLING_PROMPT}
    tg-message-batch-retelling: ${TG_MESSAGE_BATCH_RETELLING_PROMPT}

  integration:
    tg-chats-collector:
      host: ${INTEGRATION_TG_CHATS_COLLECTOR_HOST}

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  admin-ids: ${BOT_ADMIN_IDS}

logging:
  level:
    root: INFO
  console:
    enabled: true
  web-logging:
    log-body: true